Improved Duplicate Page
webriq-pagebuilder/site-template-default pull request #141
Opened 2023-06-01 02:16 UTC by mamfi-0221

Reference: link to Zoho [task](https://crmplus.zoho.com/webriqgoesmad/index.do/cxapp/projects/webriqusa#taskdetail/1512955000002969047/1512955000008982059/1512955000008982109)

Improved duplicate functionality which basically allows you to select which sections (eg: Navigation, Hero, Footer, etc.) should be duplicated unlike the default functionality which just copies the contents and they’re like references. With the new functionality, a modal presents itself and you will customize how each section gets replicated. (ref [here](https://docs.google.com/document/d/1QPh-5Jhv7n6T0gKaR0CBM3J2VQFbRIGxE_thSNQ07Cc/edit?usp=sharing))

2023-06-26 02:37 UTC, webriq commented
1. Sections - by default, all sections are duplicated as reference. If you toggle checkbox to on, this duplicates a new one and replaces with that new one which is correct now as far as I have checked.
2. Revert button - let's remove this in favor of 6 below. why is it enabled by default?
3. Layout shifting - you'll notice the checkbox moving up/down as you hover on the items. I suggest, we move the Edit/Pencel icon beside the Name of the section and only show it when they're really hovering on that name.
4. Duplicate button - as soon as you hit Duplicate, it looks very dry as if nothing happens. Would it be possible if we add a loading indicator to show it's doing its thing. 

5. Perhaps we can also add a little Delete icon ? Visually it will mark the given deleted section not to be included in the to be duplicated page. Something like a little helpertext at the bottom of each item. - This section will not be included. Also perhaps visually, change its opacity to a lower value to clearly distinct these to be deleted items from the rest.
6. Replacing a section - can we do something visually to mark that the given section has been replaced? It's the same with the rest. Also, is there a way re can revert to the original section - pretty similar with the Revert button does but individually and not as a whole.

2023-06-26 02:37 UTC, webriq requested changes
Please see my previous comments

2023-06-30 09:56 UTC, mamfi-0221 commented
Revisions committed and can been reviewed via preview URL. Thanks!

2023-07-03 01:23 UTC, webriq approved these changes

2023-07-03 02:00 UTC, merged