Update sitemap implementation using Next API
webriq-pagebuilder/site-template-default pull request #229
Opened 2024-04-26 05:40 UTC by mamfi-0221

The current sitemap implementation using `next-sitemap` plugin includes unpublished or draft pages even when filtered from the `getStaticPaths` query on target pages. Their [configuration](https://www.npmjs.com/package/next-sitemap) enables excluding certain pages, but with a very large site having multiple unpublished or draft pages without excluding the general page type makes it less configurable/workable. 

Updated implementation using Next API where this endpoint allows us to query certain pages and exclude unpublished or draft ones and gets updated on every build. Found this [thread](https://github.com/vercel/next.js/issues/9051#issuecomment-556824393) as reference to work with our same setup using Next.js SSG.

2024-04-26 06:14 UTC, webriq reviewed
I'm not sure if this matters but I see a slight difference between the sitemaps we generated vs the new one.

<img width="1387" alt="image" src="https://github.com/webriq-pagebuilder/site-template-default/assets/6467262/e0665c07-bd2e-4e7e-94ac-85a1c51c39cf">

2024-04-26 06:29 UTC, webriq requested changes
I think we also need to update our query in the `[slug].ts` page so as the unpublished page is not compiled. Same goes to blog and wherever this is applicable. Thanks

2024-04-29 06:40 UTC, webriq approved these changes

2024-04-29 06:41 UTC, dorelljames approved these changes
Good to go. Thanks!

2024-05-10 06:46 UTC, merged